# Generated by Django 4.2.16 on 2024-11-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_ptcd',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
