# Generated by Django 4.2.16 on 2024-11-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_depositoption_deposit_product_and_more'),
        ('finances', '0002_todaycurrency_img'),
    ]

    operations = [
    ]
