# Generated by Django 4.2.16 on 2024-11-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_rename_clcrdt_lend_rate_type_loanoption_crdt_lend_rate_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=20)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.CharField(max_length=100)),
                ('crdt_prdt_type', models.CharField(blank=True, max_length=100, null=True)),
                ('crdt_prdt_type_nm', models.CharField(max_length=100)),
                ('cb_name', models.CharField(max_length=100)),
                ('dcls_strt_day', models.IntegerField(blank=True, null=True)),
                ('dcls_end_day', models.IntegerField(blank=True, null=True)),
                ('fin_co_subm_day', models.IntegerField(blank=True, null=True)),
                ('crdt_lend_rate_type', models.CharField(blank=True, max_length=20, null=True)),
                ('crdt_lend_rate_type_nm', models.CharField(blank=True, max_length=20, null=True)),
                ('crdt_grad_1', models.FloatField(blank=True, null=True)),
                ('crdt_grad_4', models.FloatField(blank=True, null=True)),
                ('crdt_grad_5', models.FloatField(blank=True, null=True)),
                ('crdt_grad_6', models.FloatField(blank=True, null=True)),
                ('crdt_grad_10', models.FloatField(blank=True, null=True)),
                ('crdt_grad_11', models.FloatField(blank=True, null=True)),
                ('crdt_grad_12', models.FloatField(blank=True, null=True)),
                ('crdt_grad_13', models.FloatField(blank=True, null=True)),
                ('crdt_grad_avg', models.FloatField(default=-1)),
            ],
        ),
    ]
