# Generated by Django 4.2.16 on 2024-11-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_currency_cur_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
