name: CI/CD for Django and Vue

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Repository Checkout
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Authenticate with Google Cloud
    - name: Set up Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # 3. Configure Google Cloud SDK
    - name: Configure gcloud
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set compute/region ${{ secrets.GCP_REGION }}
        gcloud auth configure-docker

    # 4. Build and push Django image
    - name: Build and push Django image
      run: |
        docker build -t ${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/django-backend/django-backend:latest ./django-pjt
        docker push ${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/django-backend/django-backend:latest

    # 5. Deploy Django to Cloud Run
    - name: Deploy Django to Cloud Run
      run: |
        gcloud run deploy django-backend-service \
        --image ${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/django-backend/django-backend:latest \
        --platform managed \
        --region ${{ secrets.GCP_REGION }} \
        --add-cloudsql-instances ${{ secrets.GCP_PROJECT_ID }}:${{ secrets.GCP_REGION }}:${{ secrets.DATABASE_NAME }} \
        --allow-unauthenticated 

    # 6. Build and push Vue image
    - name: Build and push Vue image
      run: |
        docker build \
        --build-arg VITE_API_KEY_KAKAO_JS=${{ secrets.VITE_API_KEY_KAKAO_JS }} \
        -t ${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/vue-frontend/vue-frontend:latest ./vue-pjt
        docker push ${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/vue-frontend/vue-frontend:latest

    # 7. Deploy Vue to Cloud Run
    - name: Deploy Vue to Cloud Run
      run: |
        gcloud run deploy vue-frontend-service \
        --image ${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/vue-frontend/vue-frontend:latest \
        --platform managed \
        --region ${{ secrets.GCP_REGION }} \
        --allow-unauthenticated
